package com.aquascope.report

import com.aquascope.baseline.AnomalyThresholds
import com.aquascope.dsp.AcousticFeatures
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class ReportPoint(
    val label: String,
    val anomalyScore: Double,
    val features: AcousticFeatures,
    val timestampMs: Long = System.currentTimeMillis()
)

data class SessionReport(
    val locationLabel: String,
    val generatedAtMs: Long = System.currentTimeMillis(),
    val points: List<ReportPoint>,
    val notes: String = ""
) {
    val maxScore: Double get() = points.maxOfOrNull { it.anomalyScore } ?: 0.0
    val avgScore: Double get() = if (points.isEmpty()) 0.0 else points.map { it.anomalyScore }.average()
    val anomalyCount: Int get() = points.count { it.anomalyScore >= AnomalyThresholds.YELLOW_MAX }
    val elevatedCount: Int get() = points.count {
        it.anomalyScore >= AnomalyThresholds.GREEN_MAX && it.anomalyScore < AnomalyThresholds.YELLOW_MAX
    }
}

object ReportGenerator {

    fun statusLabel(score: Double): String = when {
        score < AnomalyThresholds.GREEN_MAX -> "NORMAL"
        score < AnomalyThresholds.YELLOW_MAX -> "ELEVATED"
        else -> "ANOMALY"
    }

    fun overallAssessment(report: SessionReport): String = when {
        report.points.isEmpty() -> "No scan points recorded."
        report.anomalyCount > 0 ->
            "${report.anomalyCount} point(s) flagged as ANOMALY — investigate moisture at those spots."
        report.elevatedCount > 0 ->
            "${report.elevatedCount} point(s) ELEVATED — re-scan or watch for change."
        else -> "All scanned points within normal range vs baseline."
    }

    /** Plain-text report suitable for Android share sheet / email. */
    fun toShareText(report: SessionReport): String {
        val fmt = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
        return buildString {
            appendLine("AQUASCOPE — Acoustic Scan Report")
            appendLine("================================")
            appendLine("Location: ${report.locationLabel}")
            appendLine("Generated: ${fmt.format(Date(report.generatedAtMs))}")
            appendLine("Points scanned: ${report.points.size}")
            appendLine("Max anomaly: ${report.maxScore.toInt()}%")
            appendLine("Avg anomaly: ${"%.1f".format(report.avgScore)}%")
            appendLine()
            appendLine("Assessment:")
            appendLine(overallAssessment(report))
            appendLine()
            appendLine("Point results")
            appendLine("-------------")
            report.points.forEachIndexed { index, p ->
                val t = fmt.format(Date(p.timestampMs))
                appendLine(
                    "${index + 1}. ${p.label}  |  ${p.anomalyScore.toInt()}%  |  ${statusLabel(p.anomalyScore)}  |  $t"
                )
                appendLine(
                    "   Resonance ${p.features.resonanceFreqHz.toInt()} Hz  ·  " +
                        "Decay ${"%.1f".format(p.features.decayTimeMs)} ms  ·  " +
                        "Centroid ${p.features.spectralCentroidHz.toInt()} Hz"
                )
            }
            if (report.notes.isNotBlank()) {
                appendLine()
                appendLine("Notes")
                appendLine("-----")
                appendLine(report.notes)
            }
            appendLine()
            appendLine("Thresholds: NORMAL < ${AnomalyThresholds.GREEN_MAX.toInt()}%  ·  " +
                "ELEVATED < ${AnomalyThresholds.YELLOW_MAX.toInt()}%  ·  ANOMALY ≥ ${AnomalyThresholds.YELLOW_MAX.toInt()}%")
            appendLine("Generated by AquaScope (hackathon prototype — calibrate before field use).")
        }
    }
}
